apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: flux-e2e-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: flux-e2e
    - name: source-repo
      value: https://github.com/flux08/flux-e2e
    - name: image-repo
      value: quay.io/fluxens0/flux-e2e
  pipelineRef:
    name: flux-e2e
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
    - name: gitops-repository
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
    - name: git-credentials
      secret:
        secretName: git-credentials
